baseURL = 'http://nciavarella.me/'
languageCode = 'en-us'
defaultContentLanguage = 'it'
title = 'nciavarella.me'
theme = 'loveit'

[params]
  version = "0.2.X"
  favicon = "/img/favicon.ico"

[author]
    name = "Niccol√≤ Ciavarella"

 [[menu.main]]
    identifier = "cv"
    name = "Info"
    url = "/menu/cv/"
